export const appConfig = {
    API_HOST: API_HOST,
    VERSION: '5fa3b9',
    SITE_URL: SITE_URL,
    ASSETS_URL: ASSETS_URL,
    API_ID: API_ID,
    PROJECT_ID: PROJECT_ID,
    U_OGS: U_OGS,
    AUTH_ADX_DOMAIN: AUTH_ADX_DOMAIN,
    ST_OGS: ST_OGS,
    ST_URL_UPLOAD: ST_URL_UPLOAD,
    APPLICATION_ENV: APPLICATION_ENV,
    SECRET_KEY: 'ANTS',
    DATE_FORMAT: 'dd/mm/yy',
    MOMENT_DATE_FORMAT: 'DD/MM/YYYY',
    TYPE_ACCOUNT_BUYER: 1,
    TYPE_ACCOUNT_SUPPORT: 2
};
